const userDesc = {
    emailIsEmpty: 'Email is empty',
    fullNameIsEmpty: 'Full name empty',
    titleIsEmpty: 'Title is empty',
    emailIsInvalid: 'Email is invalid',
    emailNotExist: "Email does not exist",
    passwordIsEmpty: 'Password is empty',
    passwordIsInvalid: 'Password is invalid',
    passwordNotExist: 'Invalid Password',
    passwordsDoNotMatch: 'Passwords do not match',
    internalServerError: 'Internal server Error',
    userNotFound: 'User not found',
    unauthorized: 'You are unauthorized for this action',
    passwordUpdate:"Password updated",
    emailSent:"Email is sent  on your registered email id",
    tokenNotValid:'Can`t update password as user not found ',
    locationIsEmpty:'Location is empty',
    descriptionIsEmpty: 'Description Is empty',
    commentIsEmpty: 'Comment Is empty',
    companyInfoIsEmpty : 'Company Info is empty',
    youtubeLink: 'Please provide a youtube link',
    facebookLink: 'Please provide a facebook link',
    twitterLink: 'Please provide a twitter link',
    instagramLink: 'Please provide an Instagram link',
    linkedinLink: 'Please provide a LinkedIn link',
    emailNotSent: 'Email Not sent',
    markDownText:'Please Enter Some Content',
    masterOnePmp: 'Please enter a valid master table ID',
    ChildOnePmp: 'Please enter a valid Child table ID',
    masterOnePmpNotFound: "Master OnePMP not found.",
    share: "Please provide a valid value.",
    emailAlreadyExist:"Email address already exist",
    limit: 'Please provide a number for limit',
    offset: 'Please provide a number for offset',
    isVerified: 'Please provide a boolean value.',
    isDisabled: 'Please provide a boolean value.',
    ontraportId: 'Please provide a valid input.',
    roleId: 'Please provide a number.',
    commentNotExist:"Comment do not exist",
    commentIdEmpty:"Comment Id cannot be null",
    pmpNotFound:"Pmp not found",
    accountNotFound:"Account not found",
    oldPassword:'Please fill your old password',
    cantSame: 'Your old and new password cannot be same',
    pmpSectionCannotBeEmpty: 'This section cannot be empty'
  };
  
  module.exports = userDesc;